### ISSUE TITLE
关于RxJs中很多函数的 第二个参数thisArg 到底有什么用 ？

### ISSUE THREAD

**Issue by adu8419** [dreambo8563/Rxjs-WishList#3]
比如：
public findIndex(predicate: function(value: T, index: number, source: Observable<T>): boolean, thisArg: any): Observable

public partition(predicate: function(value: T, index: number): boolean, thisArg: any): [Observable<T>, Observable<T>]

**Comment by dreambo8563** [comment]
你可以试下这个例子
http://dreambo8563.github.io/2016/05/12/Rxjs-Operators-Count/

``` ts
var source = Rx.Observable.range(5, 10)
    .count(function (x, i, o) {
        console.log(x, i)
        console.log(this);
    },"mockThis");

var subscription = source.subscribe(
    function (x) {
        console.log('Next: ' + x.toString());
    },
    function (err) {
        console.log('Error: ' + err);
    },
    function () {
        console.log('Completed');
    });
```

这个参数,代表,如果你predicate里用了this.这个参数就可以代表this对象
