### ISSUE TITLE
combineLatest 和 withLatestFrom的区别

### ISSUE THREAD

**Issue by dreambo8563** [dreambo8563/Rxjs-WishList#9]

**Comment by adu8419** [comment]
这个 我来说说
比如
A Stream :  --------------------------------------------->
B Stream:  ------------------------------------------------->
combineLast 表示： A Stream 每来一个新 的 就会去找B Stream中的最新的  合并为AB ，同样B Stream来了最新的也会去找A Stream中的最新的合并

而 withLatestFrom 只是 A Stream 中来了最新的 去找B Stream 中最新的合并

**Comment by AaronJin2013** [comment]
说明之前，先上宝珠图
CombineLatest：
http://reactivex.io/documentation/operators/combinelatest.html
withLatestFrom：
http://rxmarbles.com/#withLatestFrom

从宝珠图上，我们可以清楚的发现combineLast的Y是对X有追溯的，而withLatestFrom则没有追溯。
combineLast的Y有数据时，会对最近的X进行操作，withLatestFrom则只对之后的X有操作。

**Comment by dreambo8563** [comment]
来个例子, cycle.js

代码来源:
http://jsbin.com/sajewalehu/1/edit?js,output

``` js
const vtree$ = childVTree$.withLatestFrom(childValue$,
  (childVTree, value) =>
    div([
      childVTree,
      div({style: {
        backgroundColor: '#58D3D8',
        width: String(value) + 'px',
        height: String(value) + 'px',
        borderRadius: String(value * 0.5) + 'px'
      }})
    ])
  );
```

主流是childVTree$
子流childValue$
只有当有新的childVTree,也就是重新render组件的时候,才去和最新的childValue 整合成新的父组件
